# https://gist.github.com/gnarf/b103e77f37236ca72d8e
:vms:
  scarlett-cluster1:
    :hostname: "scarlett-cluster1"
    :ip: "192.168.33.100"
    :ram: 1024
    :cpu: 2
    :box: "debian/stretch64"

  scarlett-cluster2:
    :hostname: "scarlett-cluster2"
    :ip: "192.168.33.101"
    :ram: 1024
    :cpu: 2
    :box: "debian/stretch64"

  scarlett-cluster3:
    :hostname: "scarlett-cluster3"
    :ip: "192.168.33.102"
    :ram: 1024
    :cpu: 2
    :box: "debian/stretch64"

  scarlett-cluster4:
    :hostname: "scarlett-cluster4"
    :ip: "192.168.33.103"
    :ram: 1024
    :cpu: 2
    :box: "debian/stretch64"

  scarlett-ids:
    :hostname: "scarlett-ids"
    :ip: "192.168.33.104"
    :ram: 1024
    :cpu: 2
    :box: "debian/stretch64"

  scarlett-office:
    :hostname: "scarlett-office"
    :ip: "192.168.33.105"
    :ram: 1024
    :cpu: 2
    :box: "debian/stretch64"


  pine64:
    :hostname: "pine64"
    :ip: "192.168.33.106"
    :ram: 1024
    :cpu: 2
    :box: "debian/stretch64"

:groups:
  scarlett-cluster1:
    - scarlett-cluster1
  scarlett-cluster2:
    - scarlett-cluster2
  scarlett-cluster3:
    - scarlett-cluster3
  scarlett-cluster4:
    - scarlett-cluster4
  scarlett-cluster:
    - scarlett-cluster1
    - scarlett-cluster2
    - scarlett-cluster3
    - scarlett-cluster4
  scarlett_cluster:
    - scarlett-cluster1
    - scarlett-cluster2
    - scarlett-cluster3
    - scarlett-cluster4
  raspbian_servers:
    - scarlett-cluster2
    - scarlett-cluster3
  raspbians_centralized:
    - scarlett-cluster2
    - scarlett-cluster3
  raspbian:
    - scarlett-office
    - scarlett-ids
  scarlett-ids:
    - scarlett-ids
  scarlett_ids:
    - scarlett-ids
  hypriots:
    - scarlett-cluster4
  hypriot_servers:
    - scarlett-cluster4
  hypriot:
    - scarlett-cluster2
    - scarlett-cluster3
    - scarlett-cluster1
    - scarlett-cluster4
  scarlett-office:
    - scarlett-office
  scarlett_office:
    - scarlett-office
  servers:
    - scarlett-cluster2
    - scarlett-cluster3
    - scarlett-cluster1
    - scarlett-cluster4
    - scarlett-ids
    - scarlett-office
  rpi:
    - scarlett-cluster2
    - scarlett-cluster3
    - scarlett-cluster1
    - scarlett-cluster4
    - scarlett-ids
    - scarlett-office
  all_servers:
    - scarlett-cluster1
    - scarlett-cluster2
    - scarlett-cluster3
    - scarlett-cluster4
    - scarlett-ids
    - scarlett-office
  netdata_registry:
    - scarlett-office
  netdata_slaves:
    - scarlett-cluster1
    - scarlett-cluster2
    - scarlett-cluster3
    - scarlett-cluster4
    - scarlett-ids
