---
# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Include overrides specific to RHEL 7.
  include_vars: RedHat-7.yml
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version == "7"

- name: Include overrides specific to Fedora.
  include_vars: Fedora.yml
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution == "Fedora"

# Setup/install tasks.
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Ensure directories to export exist
  file: 'path="{{ item.strip().split()[0] }}" state=directory'
  with_items: "{{ nfs_exports }}"

- name: Copy exports file.
  template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: 0644
  notify: reload nfs

- name: Ensure nfs is running.
  service: "name={{ nfs_server_daemon }} state=started enabled=yes"
  when: nfs_exports|length


- name: install nfs client
  action: yum pkg=nfs-utils state=present
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version == "7"
  tags:
    - nfs

- name: Ensure rpcbind is running (CentOS)
  action: service name=rpcbind state=started enabled=yes
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version == "7"

- name: Ensure {{nfsmount}} directory exists
  action: file path={{nfsmount}} state=directory
  tags:
    - nfs
