---

- hosts: "{{ myhosts }}"
  become: True
  become_user: root
  # Elasticsearch needs this
  tasks:
    - name: "[sysctl] - vm.max_map_count=262144"
      sysctl:
        name: vm.max_map_count
        value: 262144
        sysctl_set: yes
        reload: yes
